# Generated by Django 4.1.7 on 2023-05-21 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='submitter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.user'),
        ),
    ]
