# Generated by Django 4.1.7 on 2023-05-30 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_user_alter_answer_submitter_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='submitter_id',
            new_name='submitter',
        ),
    ]
